#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-deepspeed
Version  : 0.8.2
Release  : 3
URL      : https://files.pythonhosted.org/packages/b4/7f/f81e601329fd19c5e7beabb472e0a4cb1ede8292b10df715b261f4d3a16b/deepspeed-0.8.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b4/7f/f81e601329fd19c5e7beabb472e0a4cb1ede8292b10df715b261f4d3a16b/deepspeed-0.8.2.tar.gz
Summary  : DeepSpeed library
Group    : Development/Tools
License  : MIT
Requires: pypi-deepspeed-bin = %{version}-%{release}
Requires: pypi-deepspeed-license = %{version}-%{release}
Requires: pypi-deepspeed-python = %{version}-%{release}
Requires: pypi-deepspeed-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hjson)
BuildRequires : pypi(ninja)
BuildRequires : pypi(numpy)
BuildRequires : pypi(packaging)
BuildRequires : pypi(psutil)
BuildRequires : pypi(py_cpuinfo)
BuildRequires : pypi(pydantic)
BuildRequires : pypi(torch)
BuildRequires : pypi(tqdm)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![License MIT](https://badgen.net/badge/license/MIT/blue)](https://github.com/Microsoft/DeepSpeed/blob/master/LICENSE)
[![PyPI version](https://badge.fury.io/py/deepspeed.svg)](https://pypi.org/project/deepspeed/)
[![Downloads](https://pepy.tech/badge/deepspeed)](https://pepy.tech/project/deepspeed)
[![Build](https://badgen.net/badge/build/check-status/blue)](#build-pipeline-status)

%package bin
Summary: bin components for the pypi-deepspeed package.
Group: Binaries
Requires: pypi-deepspeed-license = %{version}-%{release}

%description bin
bin components for the pypi-deepspeed package.


%package license
Summary: license components for the pypi-deepspeed package.
Group: Default

%description license
license components for the pypi-deepspeed package.


%package python
Summary: python components for the pypi-deepspeed package.
Group: Default
Requires: pypi-deepspeed-python3 = %{version}-%{release}

%description python
python components for the pypi-deepspeed package.


%package python3
Summary: python3 components for the pypi-deepspeed package.
Group: Default
Requires: python3-core
Provides: pypi(deepspeed)
Requires: pypi(hjson)
Requires: pypi(ninja)
Requires: pypi(numpy)
Requires: pypi(packaging)
Requires: pypi(psutil)
Requires: pypi(py_cpuinfo)
Requires: pypi(pydantic)
Requires: pypi(torch)
Requires: pypi(tqdm)

%description python3
python3 components for the pypi-deepspeed package.


%prep
%setup -q -n deepspeed-0.8.2
cd %{_builddir}/deepspeed-0.8.2
pushd ..
cp -a deepspeed-0.8.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678984730
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-deepspeed
cp %{_builddir}/deepspeed-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-deepspeed/689ec0681815ecc32bee639c68e7740add7bd301 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/deepspeed
/usr/bin/deepspeed.pt
/usr/bin/ds
/usr/bin/ds_bench
/usr/bin/ds_elastic
/usr/bin/ds_report
/usr/bin/ds_ssh
/usr/bin/dsr

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-deepspeed/689ec0681815ecc32bee639c68e7740add7bd301

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
